crdata: ./clashroyale.json
src_dir: ./src
spells_dir: ./ui_spells_out
output_dir: ./card-png
cards:
  ui_spells_sprite_00: sparky
  ui_spells_sprite_01: zap
  ui_spells_sprite_02: wizard
  ui_spells_sprite_03: valkyrie
  ui_spells_sprite_04: tornado
  ui_spells_sprite_05: tombstone
  ui_spells_sprite_06: three-musketeers
  ui_spells_sprite_07: ice-spirit
  ui_spells_sprite_08: skeletons
  ui_spells_sprite_09: guards
  ui_spells_sprite_10: skeleton-army
  ui_spells_sprite_11: skeleton-barrel
  ui_spells_sprite_12: gold-3
  ui_spells_sprite_13: gold-2
  ui_spells_sprite_14: gold-1
  ui_spells_sprite_15: gems-6
  ui_spells_sprite_16: gems-5
  ui_spells_sprite_17: gems-4
  ui_spells_sprite_18: gems-3
  ui_spells_sprite_19: gems-2
  ui_spells_sprite_20: gems-1
  ui_spells_sprite_21: royal-giant
  ui_spells_sprite_22: rocket
  ui_spells_sprite_23: lumberjack
  ui_spells_sprite_24: rage
  ui_spells_sprite_25: princess
  ui_spells_sprite_26: prince
  ui_spells_sprite_27: poison
  ui_spells_sprite_28: pekka
  ui_spells_sprite_29: arrows
  ui_spells_sprite_30: musketeer
  ui_spells_sprite_31: minion-horde
  ui_spells_sprite_32: minions
  ui_spells_sprite_33: mini-pekka
  ui_spells_sprite_34: miner
  ui_spells_sprite_35: mega-minion
  ui_spells_sprite_36: mega-knight
  ui_spells_sprite_37: the-log
  ui_spells_sprite_38: lightning
  ui_spells_sprite_39: lava-hound
  ui_spells_sprite_40: knight
  ui_spells_sprite_41: inferno-dragon
  ui_spells_sprite_42: ice-wizard
  ui_spells_sprite_43: ice-golem
  ui_spells_sprite_44: hog-rider
  ui_spells_sprite_45: heal
  ui_spells_sprite_46: graveyard
  ui_spells_sprite_47: gold
  ui_spells_sprite_48: goblins
  ui_spells_sprite_49: dart-goblin
  ui_spells_sprite_50: goblin-gang
  ui_spells_sprite_51: goblin-barrel
  ui_spells_sprite_52: spear-goblins
  ui_spells_sprite_53: giant-skeleton
  ui_spells_sprite_54: giant
  ui_spells_sprite_55: gems
  ui_spells_sprite_56: freeze
  ui_spells_sprite_57: flying-machine
  ui_spells_sprite_58: furnace
  ui_spells_sprite_59: fire-spirits
  ui_spells_sprite_60: goblin-hut
  ui_spells_sprite_61: fireball
  ui_spells_sprite_62: executioner
  ui_spells_sprite_63: electro-wizard
  ui_spells_sprite_64: night-witch
  ui_spells_sprite_65: dark-prince
  ui_spells_sprite_66: clone
  ui_spells_sprite_67: witch
  ui_spells_sprite_68: golem
  ui_spells_sprite_69: balloon
  ui_spells_sprite_70: cannon
  ui_spells_sprite_71: cannon-cart
  ui_spells_sprite_72: xbow
  ui_spells_sprite_73: tesla
  ui_spells_sprite_74: mortar
  ui_spells_sprite_75: inferno-tower
  ui_spells_sprite_76: elixir-collector
  ui_spells_sprite_77: bowler
  ui_spells_sprite_78: bomber
  ui_spells_sprite_79: bomb-tower
  ui_spells_sprite_80: battle-ram
  ui_spells_sprite_81: bats
  ui_spells_sprite_82: barbarians
  ui_spells_sprite_83: barbarian-hut
  ui_spells_sprite_84: bandit
  ui_spells_sprite_85: baby-dragon
  ui_spells_sprite_86: archers
  ui_spells_sprite_87: elite-barbarians
  ui_spells_sprite_88: empty-1
  ui_spells_sprite_89: empty-2
  ui_spells_sprite_90: soon
  ui_spells_sprite_91: mirror